server {
    listen 80 default_server;
    server_name _;
    return 444;
}

server {
    listen 80;
    server_name blotato.elisov.com;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name app.blotato.elisov.com;
    client_max_body_size 1M;
    location / {
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_pass http://api:3000;
    }
}

server {
    listen 80;
    server_name stand.blotato.elisov.com;
    client_max_body_size 1M;
    location / {
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_pass http://stand:3100;
    }
}
